/** Declaration file generated by dts-gen */

export = wkhtmltopdf;

declare function wkhtmltopdf(input: any, options: any, callback: any): any;

declare namespace wkhtmltopdf {
    const command: string;
    const shell: string;
}

